# ConfigureTreeSitterLinking.cmake
# 配置 Tree-sitter 库链接
#
# 此文件包含链接 Tree-sitter 库和语言库的逻辑
# 应该在 add_executable 之后调用
#
# 使用方式:
#   include(ConfigureTreeSitterLinking)
#
# 前提条件:
#   - BUILD_TREE_SITTER_SUPPORT 变量已设置
#   - TREE_SITTER_* 变量已从 ConfigureTreeSitter.cmake 设置

# 链接 Tree-sitter 库（如果启用语法高亮）
if(BUILD_TREE_SITTER_SUPPORT)
    # 使用导入目标（如果可用）
    if(TARGET TreeSitter::TreeSitter)
        target_link_libraries(pnana PRIVATE TreeSitter::TreeSitter)
    else()
        target_include_directories(pnana PRIVATE ${TREE_SITTER_INCLUDE_DIRS})
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_LIBRARIES})
    endif()
    target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_SUPPORT)

    # 链接 Tree-sitter 语言库（如果找到）
    # 注意：如果语言库未找到，对应的语言将使用原生语法高亮器
    if(TREE_SITTER_CPP_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_CPP_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_CPP)
        message(STATUS "  ✓ Tree-sitter C++ language support enabled")
    endif()
    if(TREE_SITTER_C_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_C_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_C)
        message(STATUS "  ✓ Tree-sitter C language support enabled")
    endif()
    if(TREE_SITTER_PYTHON_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_PYTHON_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_PYTHON)
        message(STATUS "  ✓ Tree-sitter Python language support enabled")
    endif()
    if(TREE_SITTER_JAVASCRIPT_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_JAVASCRIPT_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_JAVASCRIPT)
        message(STATUS "  ✓ Tree-sitter JavaScript language support enabled")
    endif()
    if(TREE_SITTER_TYPESCRIPT_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_TYPESCRIPT_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_TYPESCRIPT)
        message(STATUS "  ✓ Tree-sitter TypeScript language support enabled")
    endif()
    if(TREE_SITTER_JSON_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_JSON_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_JSON)
        message(STATUS "  ✓ Tree-sitter JSON language support enabled")
    endif()
    if(TREE_SITTER_MARKDOWN_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_MARKDOWN_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_MARKDOWN)
        message(STATUS "  ✓ Tree-sitter Markdown language support enabled")
    endif()
    if(TREE_SITTER_BASH_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_BASH_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_BASH)
        message(STATUS "  ✓ Tree-sitter Bash language support enabled")
    endif()
    if(TREE_SITTER_RUST_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_RUST_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_RUST)
        message(STATUS "  ✓ Tree-sitter Rust language support enabled")
    endif()
    if(TREE_SITTER_GO_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_GO_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_GO)
        message(STATUS "  ✓ Tree-sitter Go language support enabled")
    endif()
    if(TREE_SITTER_JAVA_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_JAVA_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_JAVA)
        message(STATUS "  ✓ Tree-sitter Java language support enabled")
    endif()
    if(TREE_SITTER_CMAKE_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_CMAKE_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_CMAKE)
        message(STATUS "  ✓ Tree-sitter CMake language support enabled")
    endif()
    if(TREE_SITTER_TCL_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_TCL_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_TCL)
        message(STATUS "  ✓ Tree-sitter TCL language support enabled")
    endif()
    if(TREE_SITTER_FORTRAN_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_FORTRAN_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_FORTRAN)
        message(STATUS "  ✓ Tree-sitter Fortran language support enabled")
    endif()
    if(TREE_SITTER_HASKELL_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_HASKELL_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_HASKELL)
        message(STATUS "  ✓ Tree-sitter Haskell language support enabled")
    endif()
    if(TREE_SITTER_LUA_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_LUA_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_LUA)
        message(STATUS "  ✓ Tree-sitter Lua language support enabled")
    endif()
    if(TREE_SITTER_YAML_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_YAML_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_YAML)
        message(STATUS "  ✓ Tree-sitter YAML language support enabled")
    endif()
    if(TREE_SITTER_XML_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_XML_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_XML)
        message(STATUS "  ✓ Tree-sitter XML language support enabled")
    endif()
    if(TREE_SITTER_CSS_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_CSS_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_CSS)
        message(STATUS "  ✓ Tree-sitter CSS language support enabled")
    endif()
    if(TREE_SITTER_SQL_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_SQL_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_SQL)
        message(STATUS "  ✓ Tree-sitter SQL language support enabled")
    endif()
    if(TREE_SITTER_RUBY_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_RUBY_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_RUBY)
        message(STATUS "  ✓ Tree-sitter Ruby language support enabled")
    endif()
    if(TREE_SITTER_PHP_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_PHP_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_PHP)
        message(STATUS "  ✓ Tree-sitter PHP language support enabled")
    endif()
    if(TREE_SITTER_SWIFT_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_SWIFT_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_SWIFT)
        message(STATUS "  ✓ Tree-sitter Swift language support enabled")
    endif()
    if(TREE_SITTER_KOTLIN_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_KOTLIN_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_KOTLIN)
        message(STATUS "  ✓ Tree-sitter Kotlin language support enabled")
    endif()
    if(TREE_SITTER_CSHARP_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_CSHARP_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_CSHARP)
        message(STATUS "  ✓ Tree-sitter C# language support enabled")
    endif()
    if(TREE_SITTER_SCALA_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_SCALA_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_SCALA)
        message(STATUS "  ✓ Tree-sitter Scala language support enabled")
    endif()
    if(TREE_SITTER_R_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_R_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_R)
        message(STATUS "  ✓ Tree-sitter R language support enabled")
    endif()
    if(TREE_SITTER_PERL_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_PERL_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_PERL)
        message(STATUS "  ✓ Tree-sitter Perl language support enabled")
    endif()
    if(TREE_SITTER_DOCKERFILE_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_DOCKERFILE_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_DOCKERFILE)
        message(STATUS "  ✓ Tree-sitter Dockerfile language support enabled")
    endif()
    if(TREE_SITTER_MAKEFILE_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_MAKEFILE_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_MAKEFILE)
        message(STATUS "  ✓ Tree-sitter Makefile language support enabled")
    endif()
    if(TREE_SITTER_VIM_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_VIM_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_VIM)
        message(STATUS "  ✓ Tree-sitter Vim language support enabled")
    endif()
    if(TREE_SITTER_POWERSHELL_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_POWERSHELL_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_POWERSHELL)
        message(STATUS "  ✓ Tree-sitter PowerShell language support enabled")
    endif()

    # 新增优化语言支持
    if(TREE_SITTER_MESON_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_MESON_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_MESON)
        message(STATUS "  ✓ Tree-sitter Meson language support enabled")
    endif()
    if(TREE_SITTER_TOML_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_TOML_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_TOML)
        message(STATUS "  ✓ Tree-sitter TOML language support enabled")
    endif()
    if(TREE_SITTER_NIM_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_NIM_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_NIM)
        message(STATUS "  ✓ Tree-sitter Nim language support enabled")
    endif()

    # 函数式编程和编译器相关语言支持
    if(TREE_SITTER_LISP_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_LISP_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_LISP)
        message(STATUS "  ✓ Tree-sitter Lisp language support enabled")
    endif()
    if(TREE_SITTER_SML_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_SML_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_SML)
        message(STATUS "  ✓ Tree-sitter SML language support enabled")
    endif()
    if(TREE_SITTER_LLVM_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_LLVM_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_LLVM)
        message(STATUS "  ✓ Tree-sitter LLVM IR language support enabled")
    endif()
    if(TREE_SITTER_RISCV_LIB)
        target_link_libraries(pnana PRIVATE ${TREE_SITTER_RISCV_LIB})
        target_compile_definitions(pnana PRIVATE BUILD_TREE_SITTER_RISCV)
        message(STATUS "  ✓ Tree-sitter RISCV Assembly language support enabled")
    endif()

    message(STATUS "Tree-sitter syntax highlighting configured")
    message(STATUS "  Note: Languages without Tree-sitter libraries will use native highlighter")
endif()
